### ISSUE TITLE
Upgrading failure from 0.0.3 to 0.0.4

### ISSUE THREAD

**Issue by ryancoughlin** [shukerullah/react-geocode#5] opened 2018-03-02 22:37 UTC
I just updated the package to 0.0.4 and am getting the following errors as soon as I boot up the project.

Let me know if there is anything else I can provide.

![screen shot 2018-03-02 at 5 36 36 pm](https://user-images.githubusercontent.com/1182341/36925325-6137be06-1e40-11e8-9bf6-15129b4bd8e9.png)

**Comment by shukerullah** [comment] 2018-03-02 22:39
`0.0.3` version worked without any errors?

**Comment by ryancoughlin** [comment] 2018-03-02 22:40
Yup! Worked great, locally but ran into https://github.com/shukerullah/react-geocode/issues/2. I saw this message and upgraded to fix that deploy issue which raised this new error.

**Comment by shukerullah** [comment] 2018-03-02 22:50
updated package to `0.0.5`, can you please try again?

**Comment by ryancoughlin** [comment] 2018-03-02 22:54
This error is now gone, but I still get the same error as the other issue when deploying:

```
5:53:58 PM: $ react-scripts build
5:53:59 PM: Creating an optimized production build...
5:54:11 PM: Failed to compile.
5:54:11 PM: Failed to minify the code from this file:
5:54:11 PM:  	./node_modules/react-geocode/index.js:8
5:54:11 PM: Read more here: http://bit.ly/2tRViJ9
5:54:11 PM: error Command failed with exit code 1.
5:54:11 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
5:54:11 PM: error Command failed with exit code 1.
5:54:11 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by shukerullah** [comment] 2018-03-02 23:09
Updated. `0.0.6` version is same now as `0.0.3`.

**Comment by shukerullah** [comment] 2018-03-02 23:11
At the moment, you can move `src/index.js` to your `src/` folder and treat it as application code. I will find its better solution later.

**Comment by shukerullah** [comment] 2018-03-03 00:24
Duplicate of #2

**Closed as completed** 2018-07-19 06:20 UTC
Labels: feature request
